Pyeongchang olympic
monun/speculation-resource-pack pull request #17
Opened 2021-09-17 06:12 UTC by NY0510

평창군

2021-09-25 15:06 UTC, obinox commented
그 README.md를 삭제해서 PR이 안되는 것 같은데 다시 올려야 하지 않을까요

2021-09-25 17:26 UTC, zlfn requested changes
README.md 복구 하셔야 merge 되실 수 있습니다.

2021-09-26 14:43 UTC, zlfn commented
README를 복구하시긴 하셨는데 PR 올려두셨을때 README에 변경사항이 있었어서 아직 conflict가 남아있네요. 변경사항을 pull 하시거나 레포 삭제하시고 다시 fork 하신다음에 PR 넣으시는게..

2021-09-27 10:58 UTC, obinox commented
다시 PR 하시는게 좋아보이는데요. 다시 올리실때는 사진도 같이 해주시면 보기 편합니다.

2021-09-27 14:52 UTC, closed without merging